name: PR CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest
    
    env:
      REFERENCES_URL: https://misaka-zerotwo.github.io/SL-References/Dev.zip
      REFERENCES_PATH: ${{ github.workspace }}/References